#!/bin/bash
echo {a..z}{a..z} | tr '' to decimal fixed
 1 file changed, 1 insertion(+), 1 deletion(-)
root@1717a4798b51:~/holbertonschool-shell/init_files_variables_and_expansions# git push
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (4/4), 359 bytes | 359.00 KiB/s, done.
Total 4 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/sachihiroo/holbertonschool-shell.git
   9e2065e..04f305d  main -> main
root@1717a4798b51:~/holbertonschool-shell/init_files_variables_and_expansions# ls
0-alias                  2-path              6-create_local_variable   README.md
10-love_exponent_breath  3-paths             7-create_global_variable
11-binary_to_decimal     4-global_variables  8-true_knowledge
1-hello_you              5-local_variables   9-divide_and_rule
root@1717a4798b51:~/holbertonschool-shell/init_files_variables_and_expansions# vi 11-binary_to_decimal
root@1717a4798b51:~/holbertonschool-shell/init_files_variables_and_expansions# git add 11-binary_to_decimal
root@1717a4798b51:~/holbertonschool-shell/init_files_variables_and_expansions# git commit -m "binary to decimal fixed"
[main 410f377] binary to decimal fixed
 1 file changed, 1 insertion(+), 1 deletion(-)
root@1717a4798b51:~/holbertonschool-shell/init_files_variables_and_expansions# git push
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (4/4), 360 bytes | 360.00 KiB/s, done.
Total 4 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/sachihiroo/holbertonschool-shell.git
   04f305d..410f377  main -> main
root@1717a4798b51:~/holbertonschool-shell/init_files_variables_and_expansions# vi 12-combinations
#!/bin/bash
echo {a..z}{a..z} | tr ' ' '\n' | grep -v oo
